// Define a list of locations
// const locations = [
//     { town: 'Nairobi', county: 'Nairobi' },
//     { town: 'Mombasa', county: 'Mombasa' },
//     { town: 'Kisumu', county: 'Kisumu' },
//     { town: 'Nakuru', county: 'Nakuru' },
//     { town: 'Eldoret', county: 'Uasin Gishu' },
//     { town: 'Thika', county: 'Kiambu' },
//     { town: 'Kisii', county: 'Kisii' },
//     { town: 'Malindi', county: 'Kilifi' },
//     { town: 'Kitale', county: 'Trans-Nzoia' },
//     { town: 'Garissa', county: 'Garissa' },
//     { town: 'Nyeri', county: 'Nyeri' },
//     { town: 'Meru', county: 'Meru' },
//     { town: 'Embu', county: 'Embu' },
//     { town: 'Machakos', county: 'Machakos' },
//     { town: 'Kakamega', county: 'Kakamega' },
//     { town: 'Bungoma', county: 'Bungoma' },
//     { town: 'Busia', county: 'Busia' },
//     { town: 'Kiambu', county: 'Kiambu' },
//     { town: 'Kericho', county: 'Kericho' },
//     { town: 'Lamu', county: 'Lamu' },
//     { town: 'Nanyuki', county: 'Laikipia' },
//     { town: 'Marsabit', county: 'Marsabit' },
//     { town: 'Voi', county: 'Taita-Taveta' },
//     { town: 'Narok', county: 'Narok' },
//     { town: 'Kitui', county: 'Kitui' },
//     { town: 'Isiolo', county: 'Isiolo' },
//     { town: 'Homa Bay', county: 'Homa Bay' },
//     { town: 'Wajir', county: 'Wajir' },
//     { town: 'Nyamira', county: 'Nyamira' },
//     { town: 'Kilifi', county: 'Kilifi' },
//     { town: 'Nyahururu', county: 'Laikipia' },
//     { town: 'Siaya', county: 'Siaya' },
//     { town: 'Kabarnet', county: 'Baringo' },
//     { town: 'Taveta', county: 'Taita-Taveta' },
//     { town: 'Lodwar', county: 'Turkana' },
//     { town: 'Kajiado', county: 'Kajiado' },
//     { town: 'Garbatula', county: 'Isiolo' },
//     { town: 'Londiani', county: 'Kericho' },
//     { town: 'Maralal', county: 'Samburu' },
//     { town: 'Kapsabet', county: 'Nandi' },
//     { town: 'Bondo', county: 'Siaya' },
//     { town: 'Wote', county: 'Makueni' },
//     { town: 'Hola', county: 'Tana River' },
//     { town: 'Oyugis', county: 'Homa Bay' },
//     { town: 'Rongai', county: 'Nakuru' },
//     { town: 'Limuru', county: 'Kiambu' },
//     { town: 'Matuu', county: 'Machakos' },
//     { town: 'Muhoroni', county: 'Kisumu' },
//     { town: 'Mwingi', county: 'Kitui' },
//     { town: 'Mandera', county: 'Mandera' },
//     { town: 'Naivasha', county: 'Nakuru' },
//     { town: 'Emali', county: 'Makueni' },
//     { town: 'Karatina', county: 'Nyeri' },
//     { town: 'Kapsowar', county: 'Elgeyo Marakwet' },
//     { town: 'Kendu Bay', county: 'Homa Bay' },
//     { town: 'Nkubu', county: 'Meru' },
//     { town: 'Keroka', county: 'Kisii' },
//     { town: 'Mwingi', county: 'Kitui' },
//     { town: 'Awendo', county: 'Migori' },
//     { town: 'Sotik', county: 'Bomet' },
//     { town: 'Sagana', county: 'Kirinyaga' },
//     { town: 'Kapsabet', county: 'Nandi' },
//     { town: 'Malaba', county: 'Busia' },
//     { town: 'Ruiru', county: 'Kiambu' },
//     { town: 'Webuye', county: 'Bungoma' },
//     { town: 'Nyahururu', county: 'Laikipia' },
//     { town: 'Bomet', county: 'Bomet' },
//     { town: 'Kikuyu', county: 'Kiambu' },
//     { town: 'Kisumu', county: 'Kisumu' },
//     { town: 'Kwale', county: 'Kwale' },
//     { town: 'Lugulu', county: 'Bungoma' },
//     { town: 'Ol Kalou', county: 'Nyandarua' },
//     { town: 'Othaya', county: 'Nyeri' },
//     { town: 'Nyahururu', county: 'Laikipia' },
//     { town: 'Limuru', county: 'Kiambu' },
//     { town: 'Kangema', county: 'Murang\'a' },
//     { town: 'Kinango', county: 'Kwale' },
//     { town: 'Maragua', county: 'Murang\'a' },
//     { town: 'Nyamira', county: 'Nyamira' },
//     { town: 'Tala', county: 'Machakos' },
//     { town: 'Nambale', county: 'Busia' },
//     { town: 'Kisii', county: 'Kisii' },
//     { town: 'Kerugoya', county: 'Kirinyaga' },
//     { town: 'Narok', county: 'Narok' },
//     { town: 'Oyugis', county: 'Homa Bay' },
//     { town: 'Londiani', county: 'Kericho' },
//     { town: 'Kathwana', county: 'Tharaka-Nithi' },
//     { town: 'Nandi Hills', county: 'Nandi' },
//     { town: 'Mweiga', county: 'Nyeri' },
//     { town: 'Kapsabet', county: 'Nandi' },
//     { town: 'Sawa Sawa', county: 'Kilifi' },
//     { town: 'Migori', county: 'Migori' },
//     { town: 'Kiserian', county: 'Kajiado' },
//     { town: 'Nyansiongo', county: 'Nyamira' },
//     { town: 'Lokichoggio', county: 'Turkana' },
//     { town: 'Nanyuki', county: 'Laikipia' },
//     { town: 'Maralal', county: 'Samburu' },
//     { town: 'Kikuyu', county: 'Kiambu' },
//     { town: 'Wajir', county: 'Wajir' },
//     { town: 'Nyahururu', county: 'Laikipia' },
//     { town: 'Bungoma', county: 'Bungoma' },
//     { town: 'Kitui', county: 'Kitui' },
//     { town: 'Homa Bay', county: 'Homa Bay' },
//     { town: 'Makueni', county: 'Makueni' },
//     { town: 'Rongai', county: 'Nakuru' },
//     { town: 'Nakuru', county: 'Nakuru' },
//     { town: 'Matuu', county: 'Machakos' },
//     { town: 'Machakos', county: 'Machakos' },
//     { town: 'Kwale', county: 'Kwale' },
//     { town: 'Kapenguria', county: 'West Pokot' },
//     { town: 'Bomet', county: 'Bomet' },
//     { town: 'Kibwezi', county: 'Makueni' },
//     { town: 'Litein', county: 'Kericho' },
//     { town: 'Oyugis', county: 'Homa Bay' },
//     { town: 'Karatina', county: 'Nyeri' },
//     { town: 'Nyahururu', county: 'Laikipia' },
//     { town: 'Kerugoya', county: 'Kirinyaga' },
//     { town: 'Maragua', county: 'Murang\'a' },
//     { town: 'Limuru', county: 'Kiambu' },
//     { town: 'Embu', county: 'Embu' },
//     { town: 'Nyeri', county: 'Nyeri' },
//     { town: 'Mwingi', county: 'Kitui' },
//     { town: 'Ruiru', county: 'Kiambu' },
//     { town: 'Narok', county: 'Narok' },
//     { town: 'Malindi', county: 'Kilifi' },
//     { town: 'Kisumu', county: 'Kisumu' },
//     { town: 'Nanyuki', county: 'Laikipia' },
//     { town: 'Mandera', county: 'Mandera' },
//     { town: 'Mumias', county: 'Kakamega' },
//     { town: 'Voi', county: 'Taita-Taveta' },
//     { town: 'Taveta', county: 'Taita-Taveta' },
//     { town: 'Kilifi', county: 'Kilifi' },
//     { town: 'Wundanyi', county: 'Taita-Taveta' },
//     { town: 'Ogembo', county: 'Kisii' },
//     { town: 'Molo', county: 'Nakuru' },
//     { town: 'Kwale', county: 'Kwale' },
//     { town: 'Kisii', county: 'Kisii' },
//     { town: 'Lugari', county: 'Kakamega' },
//     { town: 'Kapenguria', county: 'West Pokot' },
//     { town: 'Ruiru', county: 'Kiambu' },
//     { town: 'Kericho', county: 'Kericho' },
//     { town: 'Kangundo', county: 'Machakos' },
//     { town: 'Wote', county: 'Makueni' },
//     { town: 'Nambale', county: 'Busia' },
//     { town: 'Tala', county: 'Machakos' },
//     { town: 'Matuu', county: 'Machakos' },
//     { town: 'Nyahururu', county: 'Laikipia' },
//     { town: 'Naivasha', county: 'Nakuru' },
//     { town: 'Kisii', county: 'Kisii' },
//     { town: 'Oyugis', county: 'Homa Bay' },
//     { town: 'Kibwezi', county: 'Makueni' },
//     { town: 'Ngong', county: 'Kajiado' },
//     { town: 'Kitale', county: 'Trans-Nzoia' },
//     { town: 'Kapsabet', county: 'Nandi' },
//     { town: 'Kericho', county: 'Kericho' },
//     { town: 'Kajiado', county: 'Kajiado' },
//     { town: 'Nakuru', county: 'Nakuru' },
//     { town: 'Karatina', county: 'Nyeri' },
//     { town: 'Maragua', county: 'Murang\'a' },
//     { town: 'Nyahururu', county: 'Laikipia' },
//     { town: 'Lugulu', county: 'Bungoma' },
//     { town: 'Kihancha', county: 'Nyamira' },
//     { town: 'Malaba', county: 'Busia' },
//     { town: 'Ogembo', county: 'Kisii' },
//     { town: 'Maralal', county: 'Samburu' },
//     { town: 'Kitui', county: 'Kitui' },
//     { town: 'Londiani', county: 'Kericho' },
//     { town: 'Narok', county: 'Narok' },
//     { town: 'Bomet', county: 'Bomet' },
//     { town: 'Voi', county: 'Taita-Taveta' },
//     { town: 'Homa Bay', county: 'Homa Bay' },
//     { town: 'Kilifi', county: 'Kilifi' },
//     { town: 'Webuye', county: 'Bungoma' },
//     { town: 'Litein', county: 'Kericho' },
//     { town: 'Mumias', county: 'Kakamega' },
//     { town: 'Kerugoya', county: 'Kirinyaga' },
//     { town: 'Othaya', county: 'Nyeri' },
//     { town: 'Nyahururu', county: 'Laikipia' },
//     { town: 'Lugari', county: 'Kakamega' },
//     { town: 'Ngong', county: 'Kajiado' },
//     { town: 'Nyahururu', county: 'Laikipia' },
//     { town: 'Kihancha', county: 'Nyamira' },
//     { town: 'Bomet', county: 'Bomet' },
//     { town: 'Oyugis', county: 'Homa Bay' },
//     { town: 'Maralal', county: 'Samburu' },
//     { town: 'Kitui', county: 'Kitui' },
//     { town: 'Londiani', county: 'Kericho' },
//     { town: 'Narok', county: 'Narok' },
//     { town: 'Voi', county: 'Taita-Taveta' },
//     { town: 'Homa Bay', county: 'Homa Bay' },
//     { town: 'Kilifi', county: 'Kilifi' },
//     { town: 'Webuye', county: 'Bungoma' },
//     { town: 'Litein', county: 'Kericho' },
//     { town: 'Mumias', county: 'Kakamega' },
//     { town: 'Kerugoya', county: 'Kirinyaga' },
//     { town: 'Othaya', county: 'Nyeri' },
//     { town: 'Nyahururu', county: 'Laikipia' },
//     { town: 'Lugari', county: 'Kakamega' },
//     { town: 'Ngong', county: 'Kajiado' },
//     { town: 'Nyahururu', county: 'Laikipia' },
//     { town: 'Kihancha', county: 'Nyamira' },
//     { town: 'Malaba', county: 'Busia' },
//     { town: 'Maralal', county: 'Samburu' },
//     { town: 'Kitui', county: 'Kitui' },
//     { town: 'Kisii', county: 'Kisii' },
//     { town: 'Oyugis', county: 'Homa Bay' },
//     { town: 'Ruiru', county: 'Kiambu' },
//     { town: 'Nyahururu', county: 'Laikipia' },
//     { town: 'Karatina', county: 'Nyeri' },
//     { town: 'Kerugoya', county: 'Kirinyaga' },
//     { town: 'Maragua', county: 'Murang\'a' },
//     { town: 'Limuru', county: 'Kiambu' },
//     { town: 'Embu', county: 'Embu' },
//     { town: 'Nyeri', county: 'Nyeri' },
//     { town: 'Mwingi', county: 'Kitui' },
//     { town: 'Ruiru', county: 'Kiambu' },
//     { town: 'Narok', county: 'Narok' },
//     { town: 'Malindi', county: 'Kilifi' },
//     { town: 'Kisumu', county: 'Kisumu' },
//     { town: 'Nanyuki', county: 'Laikipia' },
//     { town: 'Mandera', county: 'Mandera' },
//     { town: 'Mumias', county: 'Kakamega' },
//     { town: 'Voi', county: 'Taita-Taveta' },
//     { town: 'Taveta', county: 'Taita-Taveta' },
//     { town: 'Kilifi', county: 'Kilifi' },
//     { town: 'Wundanyi', county: 'Taita-Taveta' },
//     { town: 'Ogembo', county: 'Kisii' },
//     { town: 'Molo', county: 'Nakuru' },
//     { town: 'Kwale', county: 'Kwale' },
//     { town: 'Kisii', county: 'Kisii' },
//     { town: 'Lugari', county: 'Kakamega' },
//     { town: 'Kapenguria', county: 'West Pokot' },
//     { town: 'Ruiru', county: 'Kiambu' },
//     { town: 'Kericho', county: 'Kericho' },
//     { town: 'Kangundo', county: 'Machakos' },
//     { town: 'Wote', county: 'Makueni' },
//     { town: 'Nambale', county: 'Busia' },
//     { town: 'Tala', county: 'Machakos' },
//     { town: 'Matuu', county: 'Machakos' },
//     { town: 'Nyahururu', county: 'Laikipia' },
//     { town: 'Naivasha', county: 'Nakuru' },
//     { town: 'Kisii', county: 'Kisii' },
//     { town: 'Oyugis', county: 'Homa Bay' },
//     { town: 'Kibwezi', county: 'Makueni' },
//     { town: 'Ngong', county: 'Kajiado' },
//     { town: 'Kitale', county: 'Trans-Nzoia' },
//     { town: 'Kapsabet', county: 'Nandi' },
//     { town: 'Kericho', county: 'Kericho' },
//     { town: 'Kajiado', county: 'Kajiado' },
//     { town: 'Nakuru', county: 'Nakuru' },
//     { town: 'Karatina', county: 'Nyeri' },
//     { town: 'Maragua', county: 'Murang\'a' },
//     { town: 'Nyahururu', county: 'Laikipia' },
//     { town: 'Lugulu', county: 'Bungoma' },
//     { town: 'Kihancha', county: 'Nyamira' },
//     { town: 'Malaba', county: 'Busia' },
//     { town: 'Ogembo', county: 'Kisii' },
//     { town: 'Maralal', county: 'Samburu' },
//     { town: 'Kitui', county: 'Kitui' },
//     { town: 'Londiani', county: 'Kericho' },
//     { town: 'Narok', county: 'Narok' },
//     { town: 'Bomet', county: 'Bomet' },
//     { town: 'Voi', county: 'Taita-Taveta' },
//     { town: 'Homa Bay', county: 'Homa Bay' },
//     { town: 'Kilifi', county: 'Kilifi' },
//     { town: 'Webuye', county: 'Bungoma' },
//     { town: 'Litein', county: 'Kericho' },
//     { town: 'Mumias', county: 'Kakamega' },
//     { town: 'Kerugoya', county: 'Kirinyaga' },
//     { town: 'Othaya', county: 'Nyeri' },
//     { town: 'Nyahururu', county: 'Laikipia' },
//     { town: 'Lugari', county: 'Kakamega' },
//     { town: 'Ngong', county: 'Kajiado' },
//     { town: 'Nyahururu', county: 'Laikipia' },
//     { town: 'Kihancha', county: 'Nyamira' },
//     { town: 'Bomet', county: 'Bomet' },
//     { town: 'Oyugis', county: 'Homa Bay' },
//     { town: 'Maralal', county: 'Samburu' },
//     { town: 'Kitui', county: 'Kitui' },
//     { town: 'Londiani', county: 'Kericho' },
//     { town: 'Narok', county: 'Narok' },
//     { town: 'Voi', county: 'Taita-Taveta' },
//     { town: 'Homa Bay', county: 'Homa Bay' },
//     { town: 'Kilifi', county: 'Kilifi' },
//     { town: 'Webuye', county: 'Bungoma' },
//     { town: 'Litein', county: 'Kericho' },
//     { town: 'Mumias', county: 'Kakamega' },
//     { town: 'Kerugoya', county: 'Kirinyaga' },
//     { town: 'Othaya', county: 'Nyeri' },
//     { town: 'Nyahururu', county: 'Laikipia' },
//     { town: 'Lugari', county: 'Kakamega' },
//     { town: 'Ngong', county: 'Kajiado' },
//     { town: 'Nyahururu', county: 'Laikipia' },
//     { town: 'Kihancha', county: 'Nyamira' },
//     { town: 'Malaba', county: 'Busia' },
//     { town: 'Maralal', county: 'Samburu' },
//     { town: 'Kitui', county: 'Kitui' },
//     { town: 'Kisii', county: 'Kisii' },
//     { town: 'Oyugis', county: 'Homa Bay' },
//     { town: 'Ruiru', county: 'Kiambu' },
//     { town: 'Nyahururu', county: 'Laikipia' },
//     { town: 'Karatina', county: 'Nyeri' },
//     { town: 'Kerugoya', county: 'Kirinyaga' },
//     { town: 'Maragua', county: 'Murang\'a' },
//     { town: 'Limuru', county: 'Kiambu' },
//     { town: 'Embu', county: 'Embu' },
//     { town: 'Nyeri', county: 'Nyeri' },
//     { town: 'Mwingi', county: 'Kitui' },
//     { town: 'Ruiru', county: 'Kiambu' },
//     { town: 'Narok', county: 'Narok' },
//     { town: 'Malindi', county: 'Kilifi' },
//     { town: 'Kisumu', county: 'Kisumu' },
//     { town: 'Nanyuki', county: 'Laikipia' },
//     { town: 'Mandera', county: 'Mandera' },
//     { town: 'Mumias', county: 'Kakamega' },
//     { town: 'Voi', county: 'Taita-Taveta' },
//     { town: 'Taveta', county: 'Taita-Taveta' },
//     { town: 'Kilifi', county: 'Kilifi' },
//     { town: 'Wundanyi', county: 'Taita-Taveta' },
//     { town: 'Ogembo', county: 'Kisii' },
//     { town: 'Molo', county: 'Nakuru' },
//     { town: 'Kwale', county: 'Kwale' },
//     { town: 'Kisii', county: 'Kisii' },
//     { town: 'Lugari', county: 'Kakamega' },
//     { town: 'Kapenguria', county: 'West Pokot' },
//     { town: 'Ruiru', county: 'Kiambu' },
//     { town: 'Kericho', county: 'Kericho' },
//     { town: 'Kangundo', county: 'Machakos' },
//     { town: 'Wote', county: 'Makueni' },
//     { town: 'Nambale', county: 'Busia' },
//     { town: 'Tala', county: 'Machakos' },
//     { town: 'Matuu', county: 'Machakos' },
//     { town: 'Nyahururu', county: 'Laikipia' },
//     { town: 'Naivasha', county: 'Nakuru' },
//     { town: 'Kisii', county: 'Kisii' },
//     { town: 'Oyugis', county: 'Homa Bay' },
//     { town: 'Kibwezi', county: 'Makueni' },
//     { town: 'Ngong', county: 'Kajiado' },
//     { town: 'Kitale', county: 'Trans-Nzoia' },
//     { town: 'Kapsabet', county: 'Nandi' },
//     { town: 'Kericho', county: 'Kericho' },
//     { town: 'Kajiado', county: 'Kajiado' },
//     { town: 'Nakuru', county: 'Nakuru' },
//     { town: 'Karatina', county: 'Nyeri' },
//     { town: 'Maragua', county: 'Murang\'a' },
//     { town: 'Nyahururu', county: 'Laikipia' },
//     { town: 'Lugulu', county: 'Bungoma' },
//     { town: 'Kihancha', county: 'Nyamira' },
//     { town: 'Malaba', county: 'Busia' },
//     { town: 'Ogembo', county: 'Kisii' },
//     { town: 'Maralal', county: 'Samburu' },
//     { town: 'Kitui', county: 'Kitui' },
//     { town: 'Londiani', county: 'Kericho' },
//     { town: 'Narok', county: 'Narok' },
//     { town: 'Bomet', county: 'Bomet' },
//     { town: 'Voi', county: 'Taita-Taveta' },
//     { town: 'Homa Bay', county: 'Homa Bay' },
//     { town: 'Kilifi', county: 'Kilifi' },
//     { town: 'Webuye', county: 'Bungoma' },
//     { town: 'Litein', county: 'Kericho' },
//     { town: 'Mumias', county: 'Kakamega' },
//     { town: 'Kerugoya', county: 'Kirinyaga' },
//     { town: 'Othaya', county: 'Nyeri' },
//     { town: 'Nyahururu', county: 'Laikipia' },
//     { town: 'Lugari', county: 'Kakamega' },
//     { town: 'Ngong', county: 'Kajiado' },
//     { town: 'Nyahururu', county: 'Laikipia' },
//     { town: 'Kihancha', county: 'Nyamira' },
//     { town: 'Bomet', county: 'Bomet' },
//     { town: 'Oyugis', county: 'Homa Bay' },
//     { town: 'Maralal', county: 'Samburu' },
//     { town: 'Kitui', county: 'Kitui' },
//     { town: 'Londiani', county: 'Kericho' },
//     { town: 'Narok', county: 'Narok' },
//     { town: 'Voi', county: 'Taita-Taveta' },
//     { town: 'Homa Bay', county: 'Homa Bay' },
//     { town: 'Kilifi', county: 'Kilifi' },
//     { town: 'Webuye', county: 'Bungoma' },
//     { town: 'Litein', county: 'Kericho' },
//     { town: 'Mumias', county: 'Kakamega' },
//     { town: 'Kerugoya', county: 'Kirinyaga' },
//     { town: 'Othaya', county: 'Nyeri' },
//     { town: 'Nyahururu', county: 'Laikipia' },
//     { town: 'Lugari', county: 'Kakamega' },
//     { town: 'Ngong', county: 'Kajiado' },
//     { town: 'Nyahururu', county: 'Laikipia' },
//     { town: 'Kihancha', county: 'Nyamira' },
//     { town: 'Malaba', county: 'Busia' },
//     { town: 'Maralal', county: 'Samburu' },
//     { town: 'Kitui', county: 'Kitui' },
//     { town: 'Kisii', county: 'Kisii' },
//     { town: 'Oyugis', county: 'Homa Bay' },
//     { town: 'Ruiru', county: 'Kiambu' },
//     { town: 'Nyahururu', county: 'Laikipia' },
//     { town: 'Karatina', county: 'Nyeri' },
//     { town: 'Kerugoya', county: 'Kirinyaga' },
//     { town: 'Maragua', county: 'Murang\'a' },
//     { town: 'Limuru', county: 'Kiambu' },
//     { town: 'Embu', county: 'Embu' },
//     { town: 'Nyeri', county: 'Nyeri' },
//     { town: 'Mwingi', county: 'Kitui' },
//     { town: 'Ruiru', county: 'Kiambu' },
//     { town: 'Narok', county: 'Narok' },
//     { town: 'Malindi', county: 'Kilifi' },
//     { town: 'Kisumu', county: 'Kisumu' },
//     { town: 'Nanyuki', county: 'Laikipia' },
//     { town: 'Mandera', county: 'Mandera' },
//     { town: 'Mumias', county: 'Kakamega' },
//     { town: 'Voi', county: 'Taita-Taveta' },
//     { town: 'Taveta', county: 'Taita-Taveta' },
//     { town: 'Kilifi', county: 'Kilifi' },
//     { town: 'Wundanyi', county: 'Taita-Taveta' },
//     { town: 'Ogembo', county: 'Kisii' },
//     { town: 'Molo', county: 'Nakuru' },
//     { town: 'Kwale', county: 'Kwale' },
//     { town: 'Kisii', county: 'Kisii' },
//     { town: 'Lugari', county: 'Kakamega' },
//     { town: 'Kapenguria', county: 'West Pokot' },
//     { town: 'Ruiru', county: 'Kiambu' },
//     { town: 'Kericho', county: 'Kericho' },
//     { town: 'Kangundo', county: 'Machakos' },
//     { town: 'Wote', county: 'Makueni' },
//     { town: 'Nambale', county: 'Busia' },
//     { town: 'Tala', county: 'Machakos' },
//     { town: 'Matuu', county: 'Machakos' },
//     { town: 'Nyahururu', county: 'Laikipia' },
//     { town: 'Naivasha', county: 'Nakuru' },
//     { town: 'Kisii', county: 'Kisii' },
//     { town: 'Oyugis', county: 'Homa Bay' },
//     { town: 'Kibwezi', county: 'Makueni' },
//     { town: 'Ngong', county: 'Kajiado' },
//     { town: 'Kitale', county: 'Trans-Nzoia' },
//     { town: 'Kapsabet', county: 'Nandi' },
//     { town: 'Kericho', county: 'Kericho' },
//     { town: 'Kajiado', county: 'Kajiado' },
//     { town: 'Nakuru', county: 'Nakuru' },
//     { town: 'Karatina', county: 'Nyeri' },
//     { town: 'Maragua', county: 'Murang\'a' },
//     { town: 'Nyahururu', county: 'Laikipia' },
//     { town: 'Lugulu', county: 'Bungoma' },
//     { town: 'Kihancha', county: 'Nyamira' },
//     { town: 'Malaba', county: 'Busia' },
//     { town: 'Ogembo', county: 'Kisii' },
//     { town: 'Maralal', county: 'Samburu' },
//     { town: 'Kitui', county: 'Kitui' },
//     { town: 'Londiani', county: 'Kericho' },
//     { town: 'Narok', county: 'Narok' },
//     { town: 'Bomet', county: 'Bomet' },
//     { town: 'Voi', county: 'Taita-Taveta' },
//     { town: 'Homa Bay', county: 'Homa Bay' },
//     { town: 'Kilifi', county: 'Kilifi' },
//     { town: 'Webuye', county: 'Bungoma' },
//     { town: 'Litein', county: 'Kericho' },
//     { town: 'Mumias', county: 'Kakamega' },
//     { town: 'Kerugoya', county: 'Kirinyaga' },
//     { town: 'Othaya', county: 'Nyeri' },
//     { town: 'Nyahururu', county: 'Laikipia' },
//     { town: 'Lugari', county: 'Kakamega' },
//     { town: 'Ngong', county: 'Kajiado' },
//     { town: 'Nyahururu', county: 'Laikipia' },
//     { town: 'Kihancha', county: 'Nyamira' },
//     { town: 'Bomet', county: 'Bomet' },
//     { town: 'Oyugis', county: 'Homa Bay' },
//     { town: 'Maralal', county: 'Samburu' },
//     { town: 'Kitui', county: 'Kitui' },
//     { town: 'Londiani', county: 'Kericho' },
//     { town: 'Narok', county: 'Narok' },
//     { town: 'Voi', county: 'Taita-Taveta' },
//     { town: 'Homa Bay', county: 'Homa Bay' },
//     { town: 'Kilifi', county: 'Kilifi' },
//     { town: 'Webuye', county: 'Bungoma' },
//     { town: 'Litein', county: 'Kericho' },
//     { town: 'Mumias', county: 'Kakamega' },
//     { town: 'Kerugoya', county: 'Kirinyaga' },
//     { town: 'Othaya', county: 'Nyeri' },
//     { town: 'Nyahururu', county: 'Laikipia' },
//     { town: 'Lugari', county: 'Kakamega' },
//     { town: 'Ngong', county: 'Kajiado' },
//     { town: 'Nyahururu', county: 'Laikipia' },
//     { town: 'Kihancha', county: 'Nyamira' },
//     { town: 'Malaba', county: 'Busia' },
//     { town: 'Maralal', county: 'Samburu' },
//     { town: 'Kitui', county: 'Kitui' },
//     { town: 'Kisii', county: 'Kisii' },
//     { town: 'Oyugis', county: 'Homa Bay' },
//     { town: 'Ruiru', county: 'Kiambu' },
//     { town: 'Nyahururu', county: 'Laikipia' },
//     { town: 'Karatina', county: 'Nyeri' },
//     { town: 'Kerugoya', county: 'Kirinyaga' },
//     { town: 'Maragua', county: 'Murang\'a' },
//     { town: 'Limuru', county: 'Kiambu' },
//     { town: 'Embu', county: 'Embu' },
//     { town: 'Nyeri', county: 'Nyeri' },
//     { town: 'Mwingi', county: 'Kitui' },
//     { town: 'Ruiru', county: 'Kiambu' },
//     { town: 'Narok', county: 'Narok' },
//     { town: 'Malindi', county: 'Kilifi' },
//     { town: 'Kisumu', county: 'Kisumu' },
//     { town: 'Nanyuki', county: 'Laikipia' },
//     { town: 'Mandera', county: 'Mandera' },
//     { town: 'Mumias', county: 'Kakamega' },
//     { town: 'Voi', county: 'Taita-Taveta' },
//     { town: 'Taveta', county: 'Taita-Taveta' },
//     { town: 'Kilifi', county: 'Kilifi' },
//     { town: 'Wundanyi', county: 'Taita-Taveta' },
//     { town: 'Ogembo', county: 'Kisii' },
//     { town: 'Molo', county: 'Nakuru' },
//     { town: 'Kwale', county: 'Kwale' },
//     { town: 'Kisii', county: 'Kisii' },
//     { town: 'Lugari', county: 'Kakamega' },
//     { town: 'Kapenguria', county: 'West Pokot' },
//     { town: 'Ruiru', county: 'Kiambu' },
//     { town: 'Kericho', county: 'Kericho' },
//     { town: 'Kangundo', county: 'Machakos' },
//     { town: 'Wote', county: 'Makueni' },
//     { town: 'Nambale', county: 'Busia' },
//     { town: 'Tala', county: 'Machakos' },
//     { town: 'Matuu', county: 'Machakos' },
//     { town: 'Nyahururu', county: 'Laikipia' },
//     { town: 'Naivasha', county: 'Nakuru' },
//     { town: 'Kisii', county: 'Kisii' },
//     { town: 'Oyugis', county: 'Homa Bay' },
//     { town: 'Kibwezi', county: 'Makueni' },
//     { town: 'Ngong', county: 'Kajiado' },
//     { town: 'Kitale', county: 'Trans-Nzoia' },
//     { town: 'Kapsabet', county: 'Nandi' },
//     { town: 'Kericho', county: 'Kericho' },
//     { town: 'Kajiado', county: 'Kajiado' },
//     { town: 'Nakuru', county: 'Nakuru' },
//     { town: 'Karatina', county: 'Nyeri' },
//     { town: 'Maragua', county: 'Murang\'a' },
//     { town: 'Nyahururu', county: 'Laikipia' },
//     { town: 'Lugulu', county: 'Bungoma' },
//     { town: 'Kihancha', county: 'Nyamira' },
//     { town: 'Malaba', county: 'Busia' },
//     { town: 'Ogembo', county: 'Kisii' },
//     { town: 'Maralal', county: 'Samburu' },
//     { town: 'Kitui', county: 'Kitui' },
//     { town: 'Londiani', county: 'Kericho' },
//     { town: 'Narok', county: 'Narok' },
//     { town: 'Bomet', county: 'Bomet' },
//     { town: 'Voi', county: 'Taita-Taveta' },
//     { town: 'Homa Bay', county: 'Homa Bay' },
//     { town: 'Kilifi', county: 'Kilifi' },
//     { town: 'Webuye', county: 'Bungoma' },
//     { town: 'Litein', county: 'Kericho' },
//     { town: 'Mumias', county: 'Kakamega' },
//     { town: 'Kerugoya', county: 'Kirinyaga' },
//     { town: 'Othaya', county: 'Nyeri' },
//     { town: 'Nyahururu', county: 'Laikipia' },
//     { town: 'Lugari', county: 'Kakamega' },
//     { town: 'Ngong', county: 'Kajiado' },
//     { town: 'Nyahururu', county: 'Laikipia' },
//     { town: 'Kihancha', county: 'Nyamira' },
//     { town: 'Bomet', county: 'Bomet' },
//     { town: 'Oyugis', county: 'Homa Bay' },
//     { town: 'Maralal', county: 'Samburu' },
//     { town: 'Kitui', county: 'Kitui' },
//     { town: 'Londiani', county: 'Kericho' },
//     { town: 'Narok', county: 'Narok' },
//     { town: 'Voi', county: 'Taita-Taveta' },
//     { town: 'Homa Bay', county: 'Homa Bay' },
//     { town: 'Kilifi', county: 'Kilifi' },
//     { town: 'Webuye', county: 'Bungoma' },
//     { town: 'Litein', county: 'Kericho' },
//     { town: 'Mumias', county: 'Kakamega' },
//     { town: 'Kerugoya', county: 'Kirinyaga' },
//     { town: 'Othaya', county: 'Nyeri' },
//     { town: 'Nyahururu', county: 'Laikipia' },
//     { town: 'Lugari', county: 'Kakamega' },
//     { town: 'Ngong', county: 'Kajiado' },
//     { town: 'Nyahururu', county: 'Laikipia' },
//     { town: 'Kihancha', county: 'Nyamira' },
//     { town: 'Malaba', county: 'Busia' },
//     { town: 'Maralal', county: 'Samburu' },
//     { town: 'Kitui', county: 'Kitui' },
//     { town: 'Kisii', county: 'Kisii' },
//     { town: 'Oyugis', county: 'Homa Bay' },
//     { town: 'Ruiru', county: 'Kiambu' },
//     { town: 'Nyahururu', county: 'Laikipia' },
//     { town: 'Karatina', county: 'Nyeri' },
//     { town: 'Kerugoya', county: 'Kirinyaga' },
//     { town: 'Maragua', county: 'Murang\'a' },
//     { town: 'Limuru', county: 'Kiambu' },
//     { town: 'Embu', county: 'Embu' },
//     { town: 'Nyeri', county: 'Nyeri' },
//     { town: 'Mwingi', county: 'Kitui' },
//     { town: 'Ruiru', county: 'Kiambu' },
//     { town: 'Narok', county: 'Narok' },
//     { town: 'Malindi', county: 'Kilifi' },
//     { town: 'Kisumu', county: 'Kisumu' },
//     { town: 'Nanyuki', county: 'Laikipia' },
//     { town: 'Mandera', county: 'Mandera' },
//     { town: 'Mumias', county: 'Kakamega' },
//     { town: 'Voi', county: 'Taita-Taveta' },
//     { town: 'Taveta', county: 'Taita-Taveta' },
//     { town: 'Kilifi', county: 'Kilifi' },
//     { town: 'Wundanyi', county: 'Taita-Taveta' },
//     { town: 'Ogembo', county: 'Kisii' },
//     { town: 'Molo', county: 'Nakuru' },
//     { town: 'Kwale', county: 'Kwale' },
//     { town: 'Kisii', county: 'Kisii' },
//     { town: 'Lugari', county: 'Kakamega' },
//     { town: 'Kapenguria', county: 'West Pokot' },
//     { town: 'Ruiru', county: 'Kiambu' },
//     { town: 'Kericho', county: 'Kericho' },
//     { town: 'Kangundo', county: 'Machakos' },
//     { town: 'Wote', county: 'Makueni' },
//     { town: 'Nambale', county: 'Busia' },
//     { town: 'Tala', county: 'Machakos' },
//     { town: 'Matuu', county: 'Machakos' },
//     { town: 'Nyahururu', county: 'Laikipia' },
//     { town: 'Naivasha', county: 'Nakuru' },
//     { town: 'Kisii', county: 'Kisii' },
//     { town: 'Oyugis', county: 'Homa Bay' },
//     { town: 'Kibwezi', county: 'Makueni' },
//     { town: 'Ngong', county: 'Kajiado' },
//     { town: 'Kitale', county: 'Trans-Nzoia' },
//     { town: 'Kapsabet', county: 'Nandi' },
//     { town: 'Kericho', county: 'Kericho' },
//     { town: 'Kajiado', county: 'Kajiado' },
//     { town: 'Nakuru', county: 'Nakuru' },
//     { town: 'Karatina', county: 'Nyeri' },
//     { town: 'Maragua', county: 'Murang\'a' },
//     { town: 'Nyahururu', county: 'Laikipia' },
//     { town: 'Lugulu', county: 'Bungoma' },
//     { town: 'Kihancha', county: 'Nyamira' },
//     { town: 'Malaba', county: 'Busia' },
//     { town: 'Ogembo', county: 'Kisii' },
//     { town: 'Maralal', county: 'Samburu' },
//     { town: 'Kitui', county: 'Kitui' },
//     { town: 'Londiani', county: 'Kericho' },
//     { town: 'Narok', county: 'Narok' },
//     { town: 'Bomet', county: 'Bomet' },
//     { town: 'Voi', county: 'Taita-Taveta' },
//     { town: 'Homa Bay', county: 'Homa Bay' },
//     { town: 'Kilifi', county: 'Kilifi' },
//     { town: 'Webuye', county: 'Bungoma' },
//     { town: 'Litein', county: 'Kericho' },
//     { town: 'Mumias', county: 'Kakamega' },
//     { town: 'Kerugoya', county: 'Kirinyaga' },
//     { town: 'Othaya', county: 'Nyeri' },
//     { town: 'Nyahururu', county: 'Laikipia' },
//     { town: 'Lugari', county: 'Kakamega' },
//     { town: 'Ngong', county: 'Kajiado' },
//     { town: 'Nyahururu', county: 'Laikipia' },
//     { town: 'Kihancha', county: 'Nyamira' },
//     { town: 'Bomet', county: 'Bomet' },
//     { town: 'Oyugis', county: 'Homa Bay' },
//     { town: 'Maralal', county: 'Samburu' },
//     { town: 'Kitui', county: 'Kitui' },
//     { town: 'Londiani', county: 'Kericho' },
//     { town: 'Narok', county: 'Narok' },
//     { town: 'Voi', county: 'Taita-Taveta' },
//     { town: 'Homa Bay', county: 'Homa Bay' },
//     { town: 'Kilifi', county: 'Kilifi' },
//     { town: 'Webuye', county: 'Bungoma' },
//     { town: 'Litein', county: 'Kericho' },
//     { town: 'Mumias', county: 'Kakamega' },
//     { town: 'Kerugoya', county: 'Kirinyaga' },
//     { town: 'Othaya', county: 'Nyeri' },
//     { town: 'Nyahururu', county: 'Laikipia' },
//     { town: 'Lugari', county: 'Kakamega' },
//     { town: 'Ngong', county: 'Kajiado' },
//     { town: 'Nyahururu', county: 'Laikipia' },
//     { town: 'Kihancha', county: 'Nyamira' },
//     { town: 'Malaba', county: 'Busia' },
//     { town: 'Maralal', county: 'Samburu' },
//     { town: 'Kitui', county: 'Kitui' },
//     { town: 'Kisii', county: 'Kisii' },
//     { town: 'Oyugis', county: 'Homa Bay' },
//     { town: 'Ruiru', county: 'Kiambu' },
//     { town: 'Nyahururu', county: 'Laikipia' },
//     { town: 'Karatina', county: 'Nyeri' },
//     { town: 'Kerugoya', county: 'Kirinyaga' },
//     { town: 'Maragua', county: 'Murang\'a' },
//     { town: 'Limuru', county: 'Kiambu' },
//     { town: 'Embu', county: 'Embu' },
//     { town: 'Nyeri', county: 'Nyeri' },
//     { town: 'Mwingi', county: 'Kitui' },
//     { town: 'Ruiru', county: 'Kiambu' },
//     { town: 'Narok', county: 'Narok' },
//     { town: 'Malindi', county: 'Kilifi' },
//     { town: 'Kisumu', county: 'Kisumu' },
//     { town: 'Nanyuki', county: 'Laikipia' },
//     { town: 'Mandera', county: 'Mandera' },
//     { town: 'Mumias', county: 'Kakamega' },
//     { town: 'Voi', county: 'Taita-Taveta' },
//     { town: 'Taveta', county: 'Taita-Taveta' },
//     { town: 'Kilifi', county: 'Kilifi' },
//     { town: 'Wundanyi', county: 'Taita-Taveta' },
//     { town: 'Ogembo', county: 'Kisii' },
//     { town: 'Molo', county: 'Nakuru' },
//     { town: 'Kwale', county: 'Kwale' },
//     { town: 'Kisii', county: 'Kisii' },
//     { town: 'Lugari', county: 'Kakamega' },
//     { town: 'Kapenguria', county: 'West Pokot' },
//     { town: 'Ruiru', county: 'Kiambu' },
//     { town: 'Kericho', county: 'Kericho' },
//     { town: 'Kangundo', county: 'Machakos' },
//     { town: 'Wote', county: 'Makueni' },
//     { town: 'Nambale', county: 'Busia' },
//     { town: 'Tala', county: 'Machakos' },
//     { town: 'Matuu', county: 'Machakos' },
//     { town: 'Nyahururu', county: 'Laikipia' },
//     { town: 'Naivasha', county: 'Nakuru' },
//     { town: 'Kisii', county: 'Kisii' },
//     { town: 'Oyugis', county: 'Homa Bay' },
//     { town: 'Kibwezi', county: 'Makueni' },
//     { town: 'Ngong', county: 'Kajiado' },
//     { town: 'Kitale', county: 'Trans-Nzoia' },
//     { town: 'Kapsabet', county: 'Nandi' },
//     { town: 'Kericho', county: 'Kericho' },
//     { town: 'Kajiado', county: 'Kajiado' },
//     { town: 'Nakuru', county: 'Nakuru' },
//     { town: 'Karatina', county: 'Nyeri' },
//     { town: 'Maragua', county: 'Murang\'a' },
//     { town: 'Nyahururu', county: 'Laikipia' },
//     { town: 'Lugulu', county: 'Bungoma' },
//     { town: 'Kihancha', county: 'Nyamira' },
//     { town: 'Malaba', county: 'Busia' },
//     { town: 'Ogembo', county: 'Kisii' },
//     { town: 'Maralal', county: 'Samburu' },
//     { town: 'Kitui', county: 'Kitui' },
//     { town: 'Londiani', county: 'Kericho' },
//     { town: 'Narok', county: 'Narok' },
//     { town: 'Bomet', county: 'Bomet' },
//     { town: 'Voi', county: 'Taita-Taveta' },
//     { town: 'Homa Bay', county: 'Homa Bay' },
//     { town: 'Kilifi', county: 'Kilifi' },
//     { town: 'Webuye', county: 'Bungoma' },
//     { town: 'Litein', county: 'Kericho' },
//     { town: 'Mumias', county: 'Kakamega' },
//     { town: 'Kerugoya', county: 'Kirinyaga' },
//     { town: 'Othaya', county: 'Nyeri' },
//     { town: 'Nyahururu', county: 'Laikipia' },
//     { town: 'Lugari', county: 'Kakamega' },
//     { town: 'Ngong', county: 'Kajiado' },
//     { town: 'Nyahururu', county: 'Laikipia' },
// ]
const locations = [
    { town: 'Nairobi', county: 'Nairobi' },
    { town: 'Mombasa', county: 'Mombasa' },
    { town: 'Kisumu', county: 'Kisumu' },
    { town: 'Nakuru', county: 'Nakuru' },
]
const API_URL = "https://mangi-property-xo74.vercel.app/api/properties";

document.addEventListener('DOMContentLoaded', () => {
    document.getElementById('location').addEventListener('input', handleLocationInput);
    document.getElementById('addPropertyBtn').addEventListener('click', () => openForm());
    document.getElementById('propertyFormInner').addEventListener('submit', submitPropertyForm);
    fetchProperties();
});

function openForm() {
    document.getElementById('propertyForm').style.display = 'block';
    clearFormFields();
}

function closeForm() {
    document.getElementById('propertyForm').style.display = 'none';
}

function clearFormFields() {
    document.getElementById('propertyFormInner').reset();
    document.getElementById('propertyId').value = '';
    document.getElementById('imagePreview').style.display = 'none';
}

async function submitPropertyForm(event) {
    event.preventDefault();
    const propertyId = document.getElementById('propertyId').value;
    const formData = new FormData(document.getElementById('propertyFormInner'));
    const url = propertyId ? `${API_URL}/${propertyId}` : API_URL;

    try {
        const response = await fetch(url, {
            method: propertyId ? 'PUT' : 'POST',
            body: formData,
        });
        if (response.ok) {
            alert('Property saved successfully!');
            closeForm();
            fetchProperties();
        } else {
            const result = await response.json();
            throw new Error(result.message);
        }
    } catch (error) {
        console.error('Save property failed:', error);
        alert(`Error: ${error.message}`);
    }
}

async function fetchProperties() {
    try {
        const response = await fetch(API_URL);
        const properties = await response.json();
        displayProperties(properties);
    } catch (error) {
        console.error('Failed to fetch properties:', error);
        alert('Failed to fetch properties. Please try again later.');
    }
}

function displayProperties(properties) {
    const display = document.getElementById('propertiesDisplay');
    display.innerHTML = properties.map(property => `
        <tr>
            <td><img src="${property.imagePath || ''}" alt="Property Image" style="width:100px; height: auto; cursor: pointer;" onclick="previewImage('${property.imagePath || ''}')"></td>
            <td>${property.name || '-'}</td>
            <td>${property.location || '-'}</td>
            <td>${property.description || '-'}</td>
            <td>${property.price || '-'}</td>
            <td>${property.type || '-'}</td>
            <td>${property.period || '-'}</td>
            <td>
                <button class="btn" onclick="editProperty('${property.id}')"><i class="fas fa-edit"></i>Edit</button>
                <button class="btn" onclick="deleteProperty('${property.id}')"><i class="fas fa-trash-alt"></i>Delete</button>
            </td>
        </tr>
    `).join('');
}

async function editProperty(id) {
    const url = `${API_URL}/${id}`;

    try {
        const response = await fetch(url);

        if (!response.ok) {
            throw new Error('Failed to fetch property details');
        }

        const property = await response.json();

        document.getElementById('propertyId').value = property.id;
        document.getElementById('name').value = property.name || '';
        document.getElementById('location').value = property.location || '';
        document.getElementById('description').value = property.description || '';
        document.getElementById('price').value = property.price || '';
        document.getElementById('type').value = property.propertyType || ''; // Updated property type field name
        document.getElementById('period').value = property.period || '';

        document.getElementById('propertyForm').style.display = 'block';
    } catch (error) {
        console.error('Edit property failed:', error);
        alert(`Error: ${error.message}`);
    }
}

async function deleteProperty(id) {
    try {
        const response = await fetch(`${API_URL}/${id}`, { method: 'DELETE' });
        if (response.ok) {
            alert('Property deleted successfully!');
            fetchProperties();
        } else {
            throw new Error('Failed to delete property');
        }
    } catch (error) {
        console.error('Delete property failed:', error);
        alert(`Error: ${error.message}`);
    }
}

function handleLocationInput() {
    const input = this.value.toLowerCase();
    const dropdown = document.getElementById('locationDropdown');

    // Clear previous options
    dropdown.innerHTML = '';

    // Filter locations based on input
    const filteredLocations = locations.filter(location => location.town.toLowerCase().includes(input));

    // Add filtered options to the dropdown
    filteredLocations.forEach(location => {
        const option = document.createElement('div');
        option.textContent = location.town;
        option.classList.add('dropdown-option');
        option.addEventListener('click', () => {
            document.getElementById('location').value = location.town;
            dropdown.innerHTML = '';
        });
        dropdown.appendChild(option);
    });

    // Show or hide the dropdown based on input
    if (filteredLocations.length > 0) {
        dropdown.style.display = 'block';
    } else {
        dropdown.style.display = 'none';
    }
}

function previewImage(imagePath) {
    const modal = document.getElementById('imagePreviewModal');
    const modalImg = document.getElementById('modalImage');
    modal.style.display = 'block';
    modalImg.src = imagePath;
}

// Close the modal when clicking outside of the image
window.onclick = function (event) {
    const modal = document.getElementById('imagePreviewModal');
    if (event.target == modal) {
        modal.style.display = 'none';
    }
}